apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline-tutorial-run
spec:
  serviceAccount: docker-auth-sa
  pipelineRef:
    name: pipeline-tutorial
  trigger:
    type: manual
  resources:
    - name: source-repo
      resourceRef:
        name: git
    - name: image-web
      resourceRef:
        name: image-web
    - name: image-app
      resourceRef:
        name: image-app
